### ISSUE TITLE
on a server

### ISSUE THREAD

**Issue by lindseyrie** [dennisblokland/Curio#6]
I can't start a server with curio on it i get the following error

> java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at com.denbukki.curio.items.ItemBase.getDescriptionText(ItemBase.java:33)
	at com.denbukki.curio.items.ItemBase.<init>(ItemBase.java:21)
	at com.denbukki.curio.items.BaublesItemBase.<init>(BaublesItemBase.java:25)
	at com.denbukki.curio.items.ItemRing.<init>(ItemRing.java:8)
	at com.denbukki.curio.items.CurioItems.<clinit>(CurioItems.java:11)
	at com.denbukki.curio.blocks.CurioBlocks.<clinit>(CurioBlocks.java:16)
	at com.denbukki.curio.Curio$RegsitrationHandler.registerBlocks(Curio.java:71)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_80_RegsitrationHandler_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:775)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 18 more
Caused by: java.lang.NullPointerException
>
>

**Comment by dennisblokland** [comment]
fixed version has been uploaded
